name: Kate Hayden
favicon: null
layout_spectrum: 0.7063
typography_spectrum: 0.16261
title: Kate Hayden Health and Fitness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f12691'
    - '#7f7f7f'
    - '#3f057d'
    - '#f784c0'
  brandStrength: 0.5400408112909645
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
