name: KateHayden
favicon: null
layout_spectrum: 0.8183197763282806
typography_spectrum: 0.37367915362119675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5400408112909645
  lightness: 0.007098662434145808
  saturation: 0.07750146463513374
  rhythmicContrast: 0.31595461280085146
purpose: []
