typography_spectrum: 0.16261
color:
  brandColors:
    - '#ffffff'
    - '#f12691'
    - '#7f7f7f'
    - '#3f057d'
    - '#f784c0'
  brandStrength: 0.5400408112909645
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99176
analytics:
  google: null
  facebook: null
  twitter: null
name: Kate Hayden
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: www.winningwellbeing.com
    type: external
  - name: 'About '
    id: 631c10d8-af22-45ef-9f81-334772d5a781
    type: content
favicon: null
title: Kate Hayden Health and Fitness
purpose: []
